# .env.dev
spring.config.import=optional:file:.env.dev[.properties]
# AI 설정
# https://console.groq.com/keys
spring.ai.openai.api-key=${GROQ_API_KEY:please-input-key}
# https://console.groq.com/docs/openai
spring.ai.openai.base-url=https://api.groq.com/openai/v1
# https://console.groq.com/docs/models
# https://console.groq.com/docs/rate-limits
spring.ai.openai.chat.model=openai/gpt-oss-120b
# 로깅 설정
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
# DB 설정
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# MyBatis 설정
# org.example.springai2 <- 본인 프로젝트 아티팩트
logging.level.org.example.springai2.mapper=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# JPA/Hibernate
# DDL (create X, update or validate)
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=create
# MyBatis로 생성된 테이블을 바로 사용
# SQL 로그로 확인
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true