# .env.dev
spring.config.import=optional:file:.env.dev[.properties]
# AI 설정
# https://console.groq.com/keys
spring.ai.openai.api-key=${GROQ_API_KEY:please-input-key}
# https://console.groq.com/docs/openai
spring.ai.openai.base-url=https://api.groq.com/openai/v1
# https://console.groq.com/docs/models
# https://console.groq.com/docs/rate-limits
spring.ai.openai.chat.model=openai/gpt-oss-120b